services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: "redis:latest"
  api:
    build:
      dockerfile: Dockerfile
      context: ./server
    expose:
      - "5001"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    depends_on:
      - postgres
      - redis
    # We should not add this while deploying to cloud service, but required only for spinning the app in production mode in local machine
    # ports:
    #   - "5001:5001"
  worker:
    build:
      dockerfile: Dockerfile
      context: ./worker
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  ui:
    build:
      dockerfile: Dockerfile
      context: ./client
      args:
        # For prod mode, we build the react app. So need this as build argument instead of runtime env variable
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    expose:
      - "3000"
