version: "1"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: "redis:latest"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
