upstream ui_service {
    # Match the port exposed in your UI Dockerfile
    server ui:3000;
}

upstream api_service {
    # Match your Express server port
    server api:5001;
}

server {
    listen 80;

    location / {
        proxy_pass http://ui_service;
    }

    location /api {
        proxy_pass http://api_service;
    }
}